export const APP_CONSTANTS = {
  tenant_auth_types: {
    Form: 1,
    Saml: 2,
    Ldap: 3,
  },
  control_display_modes: {
    visible: 33,
    require: 34,
    disabled: 35,
    display_read_only: 36,
    none_hidden: 37,
  },
  control_types: {
    alphaNumeric: 1,
    alphaOnly: 2,
    email: 3,
    date: 4,
    dateAndTime: 5,
    password: 6,
    phoneNumber: 7,
    integer: 8,
    decimal: 9,
    checkbox: 10,
    dropdownMultiselect: 11,
    dropdown: 12,
    textArea: 13,
    fileUpload: 14,
    hyperlink: 15,
    submit: 16,
    treeViewSingle: 17,
    treeViewMulti: 18,
    barChart: 19,
    lineChart: 20,
    pieChart: 21,
    geoLocation: 22,
    htmlEditor: 23,
    htmlParser: 24,
    currency: 25,
    image: 26,
    month: 27,
    time: 28,
    reorderList: 29,
    switch: 30,
    list: 31,
    url: 32,
    hyperlinkRow: 33,
    addTableRow: 34,
    deleteTableRow: 35,
    markdownParser: 36,
    colorPicker: 37,
    fieldConditionTable: 38,
  },
  platforms: {
    both: 20,
    web: 21,
    mobile: 22,
  },
  page_display_locations: {
    sidebar: 17,
    quicklist: 18,
    none: 19,
  },
  page_types: {
    form: 23,
    report: 24,
    schedule: 38,
  },
  page_binding_types: {
    function: 25,
  },
  section_display_modes: {
    expand: 28,
    collapse: 29,
    none: 30,
  },
  child_display_modes: {
    form: 31,
    dataTable: 32,
    dataTableReport: 39,
    dataTableReportAdvance: 40,
    googleMap: 41,
    cardItem: 259,
  },
} as const
