import type { LucideIcon } from 'lucide-react'
import {
  MessageSquare, BookOpen, LayoutDashboard, Book, User, Search, Folder,
  FileText, Home, Settings, Menu, Grid, List, Calendar, Clock, Building,
  Users, UserPlus, UserCheck, Shield, Key, Lock, Unlock, Package, Truck,
  Warehouse, Tag, Barcode, Monitor, HardDrive, Mail, Phone, Headphones,
  MessageCircle, Bell, AlertTriangle, FileSpreadsheet, FileImage,
  Download, Upload, Printer, DollarSign, CreditCard, Receipt, TrendingUp,
  BarChart3, PieChart, Bot, Layout, File, BadgeCheck, Contact, UserMinus,
  Briefcase, Wallet, Banknote, Coins, ShoppingCart, Boxes, ClipboardList,
  Cpu, Server, Terminal, Code2, Bug, Database, LineChart, GaugeCircle,
  Activity, Sparkles, BrainCircuit, Rocket, Wand2, Flame, Camera, Image,
  Eye, EyeOff, Globe, MapPin, Compass, Star, Trash, Edit, Plus, Minus, X,
  Check, ChevronDown, ChevronUp, ChevronLeft, ChevronRight, Info,
  HelpCircle, ExternalLink, ClipboardCheck, QrCode,
  // common extras used internally
  FolderOpen, Building2, BarChart2, LayoutGrid,
} from 'lucide-react'

/**
 * Canonical mapping from icon name (as stored in the backend schema) → Lucide component.
 * Includes the exact names from the app icon list plus lowercase / alias variants so
 * schema values like "dashboard" or "bar_chart" also resolve correctly.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  // ── Primary list (exact names) ───────────────────────────────────────────────
  MessageSquare, BookOpen, LayoutDashboard, Book, User, Search, Folder,
  FileText, Home, Settings, Menu, Grid, List, Calendar, Clock, Building,
  Users, UserPlus, UserCheck, Shield, Key, Lock, Unlock, Package, Truck,
  Warehouse, Tag, Barcode, Monitor, HardDrive, Mail, Phone, Headphones,
  MessageCircle, Bell, AlertTriangle, FileSpreadsheet, FileImage,
  Download, Upload, Printer, DollarSign, CreditCard, Receipt, TrendingUp,
  BarChart3, PieChart, Bot, Layout, File, BadgeCheck, Contact, UserMinus,
  Briefcase, Wallet, Banknote, Coins, ShoppingCart, Boxes, ClipboardList,
  Cpu, Server, Terminal, Code2, Bug, Database, LineChart, GaugeCircle,
  Activity, Sparkles, BrainCircuit, Rocket, Wand2, Flame, Camera, Image,
  Eye, EyeOff, Globe, MapPin, Compass, Star, Trash, Edit, Plus, Minus, X,
  Check, ChevronDown, ChevronUp, ChevronLeft, ChevronRight, Info,
  HelpCircle, ExternalLink, ClipboardCheck, QrCode,

  // ── Aliases — common Material UI / snake_case / alternate names ──────────────
  Dashboard:       LayoutDashboard,
  dashboard:       LayoutDashboard,
  layout_dashboard: LayoutDashboard,
  home:            Home,
  settings:        Settings,
  search:          Search,
  folder:          Folder,
  folder_open:     FolderOpen,
  FolderOpen,
  file_text:       FileText,
  file:            File,
  user:            User,
  users:           Users,
  person:          User,
  people:          Users,
  group:           Users,
  Building2,
  building2:       Building2,
  company:         Building2,
  office:          Building,
  chat:            MessageSquare,
  message:         MessageSquare,
  message_square:  MessageSquare,
  message_circle:  MessageCircle,
  mail:            Mail,
  email:           Mail,
  phone:           Phone,
  bell:            Bell,
  notification:    Bell,
  alert:           AlertTriangle,
  warning:         AlertTriangle,
  info:            Info,
  help:            HelpCircle,
  question:        HelpCircle,
  calendar:        Calendar,
  clock:           Clock,
  time:            Clock,
  tag:             Tag,
  barcode:         Barcode,
  qr_code:         QrCode,
  package:         Package,
  box:             Package,
  boxes:           Boxes,
  truck:           Truck,
  shipping:        Truck,
  warehouse:       Warehouse,
  inventory:       Boxes,
  shopping_cart:   ShoppingCart,
  cart:            ShoppingCart,
  dollar:          DollarSign,
  dollar_sign:     DollarSign,
  money:           DollarSign,
  credit_card:     CreditCard,
  receipt:         Receipt,
  wallet:          Wallet,
  banknote:        Banknote,
  coins:           Coins,
  trending_up:     TrendingUp,
  bar_chart:       BarChart3,
  BarChart:        BarChart3,
  BarChart2,
  bar_chart2:      BarChart2,
  bar_chart3:      BarChart3,
  pie_chart:       PieChart,
  line_chart:      LineChart,
  ShowChart:       LineChart,
  gauge:           GaugeCircle,
  gauge_circle:    GaugeCircle,
  activity:        Activity,
  monitor:         Monitor,
  hard_drive:      HardDrive,
  cpu:             Cpu,
  server:          Server,
  database:        Database,
  terminal:        Terminal,
  code:            Code2,
  code2:           Code2,
  bug:             Bug,
  upload:          Upload,
  download:        Download,
  printer:         Printer,
  image:           Image,
  camera:          Camera,
  eye:             Eye,
  eye_off:         EyeOff,
  globe:           Globe,
  map_pin:         MapPin,
  location:        MapPin,
  compass:         Compass,
  star:            Star,
  favorite:        Star,
  rocket:          Rocket,
  sparkles:        Sparkles,
  brain:           BrainCircuit,
  brain_circuit:   BrainCircuit,
  bot:             Bot,
  ai:              Bot,
  wand:            Wand2,
  wand2:           Wand2,
  flame:           Flame,
  fire:            Flame,
  shield:          Shield,
  security:        Shield,
  key:             Key,
  lock:            Lock,
  unlock:          Unlock,
  briefcase:       Briefcase,
  work:            Briefcase,
  layout:          Layout,
  grid:            Grid,
  LayoutGrid,
  layout_grid:     LayoutGrid,
  list:            List,
  clipboard_list:  ClipboardList,
  clipboard_check: ClipboardCheck,
  badge_check:     BadgeCheck,
  check:           Check,
  x:               X,
  close:           X,
  plus:            Plus,
  add:             Plus,
  minus:           Minus,
  remove:          Minus,
  trash:           Trash,
  delete:          Trash,
  edit:            Edit,
  pencil:          Edit,
  external_link:   ExternalLink,
  link:            ExternalLink,
  headphones:      Headphones,
  support:         Headphones,
  contact:         Contact,
  user_plus:       UserPlus,
  user_minus:      UserMinus,
  user_check:      UserCheck,
  book:            Book,
  book_open:       BookOpen,
  knowledge:       BookOpen,
  docs:            FileText,
  report:          FileSpreadsheet,
  file_spreadsheet: FileSpreadsheet,
  file_image:      FileImage,
}

/** Resolve a backend icon name to a Lucide component. Falls back to FileText. */
export function resolveIcon(name?: string | null, fallback: LucideIcon = FileText): LucideIcon {
  if (!name) return fallback
  // 1. Exact match
  if (ICON_MAP[name]) return ICON_MAP[name]
  // 2. Case-insensitive match
  const lower = name.toLowerCase()
  if (ICON_MAP[lower]) return ICON_MAP[lower]
  // 3. PascalCase dynamic lookup in full lucide-react namespace
  return fallback
}
